<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Country</name>
   <tag></tag>
   <elementGuidId>0a4b85af-c24b-47c4-9f92-d25252e2fdf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='countryCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//select[@id='countryCode']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
