<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save Card_checkmark</name>
   <tag></tag>
   <elementGuidId>853cef50-a437-434f-b0ad-4cde2d03c0fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='wrapper']/div[2]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/form[1]/div[5]/section[1]/div[4]/div[1]/label[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;braintree-form&quot;)/section[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-4 col-sm-5 col-xs-12&quot;]/label[@class=&quot;checkbox-label&quot;]/i[@class=&quot;checkmark&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='braintree-form']/section/div[4]/div/label/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/i</value>
   </webElementXpaths>
</WebElementEntity>
