<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Log in Button from header</name>
   <tag></tag>
   <elementGuidId>e2f2c1c2-b71e-4b8e-9e17-f8fb233bb4b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;header_partial&quot;]/div/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:void(0)' and (text() = 'Log In' or . = 'Log In')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;loginPopup__main-form&quot;]/div[2]/a[1]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logIn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>loginModalShow(false, null, 'signin');return false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_partial&quot;)/div[@class=&quot;rightMenu&quot;]/ul[1]/li[@class=&quot;subMenu&quot;]/a[@class=&quot;logIn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
