<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Atlanta</name>
   <tag></tag>
   <elementGuidId>74a2ff48-ed0a-4ba4-9ee6-bac3282d9d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header/div[1]/div[1]/nav[1]/ul[1]/li[1]/div[1]/ul[1]/li[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
