<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Houston</name>
   <tag></tag>
   <elementGuidId>f12b25e2-c834-44c8-aa85-ef9b386a9bc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header/div[1]/div[1]/nav[1]/ul[1]/li[1]/div[1]/ul[1]/li[7]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
