<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manchester</name>
   <tag></tag>
   <elementGuidId>fc2ae063-7e4b-4e1b-b944-a68d9ece5ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header/div[1]/div[1]/nav[1]/ul[1]/li[1]/div[1]/ul[1]/li[10]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
