<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Oakland</name>
   <tag></tag>
   <elementGuidId>35a6f035-65dd-44ab-9f0f-2ecf6c60340a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header/div[1]/div[1]/nav[1]/ul[1]/li[1]/div[1]/ul[1]/li[13]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
