<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Webinar</name>
   <tag></tag>
   <elementGuidId>35b44ac4-02e4-4501-a5e7-be729fec2e10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Webinar')]/preceding::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//span[contains(text(),'Webinar')]/preceding::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
