<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Webinar</name>
   <tag></tag>
   <elementGuidId>2cd10001-fb7b-4e29-b40a-bcaf065c741b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Webinar')]/preceding::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//span[contains(text(),'Webinar')]/preceding::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
