<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Recaptcha</name>
   <tag></tag>
   <elementGuidId>e8af488f-42e1-4db2-9871-713a0aea3441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='wrapper']/div[@id='content']/section[1]/div[1]/section[1]/div[1]/div[1]/div[2]/form[1]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
